### ISSUE TITLE
Abort! Check example tree file format or check file order in command line

### ISSUE THREAD

**Issue by rieverg** [tomsauv/TREE2FASTA#2]
Hi, what am I doing wrong? The program worked just fine on the example files, but it doesn't like my tree file for some reason, even though i saved it according to your instruction on working with FigTree. Any help would be appreciated

**Comment by tomsauv** [comment]
Hello, could you send your tree file to make sure that figtree saved your
edits?

**Comment by rieverg** [comment]
There's a Nexus tag in the first line and the colour names are next to the
taxa labels like in the example file, so I really am not sure what is wrong
with it

вт, 16 июл. 2024 г. в 16:50, Thomas Sauvage ***@***.***>:

> Hello, could you send your tree file to make sure that figtree saved your
> edits?
>

**Comment by tomsauv** [comment]
This error message comes if the first line of the edited tree file does not contain #NEXUS. Since you mention it's there, the other case it happens is if you switch the order of the command line arguments. The tree file should be first and then the fasta file second. If you can send me your files at tomsauv@gmail.com, I can help troubleshoot.
